#!/bin/sh

EMAIL="decke@bluelife.at"
PUBKEY="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJKwhL6VlH5cHe/WKx8ODHas8m/PwqUpa8MYE4MBZosp decke@bluelife.at-2016"
HOSTNAME=`hostname`

if [ "${2}" = "POST-INSTALL" ] ; then

  # set hostname in sshd banner
  sed -i "" 's/{HOSTNAME}/'${HOSTNAME}'/g' /etc/motd_ssh

  # redirect all system emails to myself
  sed -i "" 's/me@my.domain/'${EMAIL}'/g' /etc/mail/aliases
  sed -i "" 's/# root:/root:/g' /etc/mail/aliases

  # switch from sendmail(8) to dma(8)
  sed -i "" 's|/usr/libexec/sendmail/sendmail|/usr/libexec/dma|g' /etc/mail/mailer.conf

  if [ ! -d "/root/.ssh" ]; then
    mkdir /root/.ssh
    chmod 0700 /root/.ssh
  fi

  if [ ! -f "/root/.ssh/authorized_keys" ]; then
    echo ${PUBKEY} >> /root/.ssh/authorized_keys
    chmod 0600 /root/.ssh/authorized_keys
  fi
fi
