# $FreeBSD$

PORTNAME=	kodi-platform
PORTVERSION=	20170306
CATEGORIES=	devel

MAINTAINER=	decke@FreeBSD.org
COMMENT=	Kodi platform support library

USE_GITHUB=	yes
GH_ACCOUNT=	xbmc
GH_TAGNAME=	36fb493

USES=		cmake

.include <bsd.port.mk>
