# $FreeBSD$

PORTNAME=	kodi-platform
PORTVERSION=	20170306
CATEGORIES=	devel

MAINTAINER=	decke@FreeBSD.org
COMMENT=	Kodi platform support library

LICENSE=	GPLv2+

USES=		cmake

USE_GITHUB=	yes
GH_ACCOUNT=	xbmc
GH_TAGNAME=	36fb493

USE_LDCONFIG=	yes

.include <bsd.port.mk>
