# $FreeBSD$

# CAUTION: name conflict with games/wtf

PORTNAME=	wtf
DISTVERSION=	0.5.0
CATEGORIES=	sysutils

MAINTAINER=	decke@FreeBSD.org
COMMENT=	Personal terminal-based dashboard utility

LICENSE=	MPL20
LICENSE_FILE=	${WRKSRC}/LICENSE.md

USES=		go
USE_GITHUB=	yes

GH_ACCOUNT=	wtfutil
GO_PKGNAME=	github.com/wtfutil/wtf

PLIST_FILES=	bin/${PORTNAME}

.include <bsd.port.mk>
