# $FreeBSD: head/mail/py-aiosmtpd/Makefile 448957 2017-08-30 03:04:08Z acm $

PORTNAME=	aiosmtpd
PORTVERSION=	1.1
PORTREVISION=	1
CATEGORIES=	mail python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	acm@FreeBSD.org
COMMENT=	Asyncio based SMTP server

LICENSE=	APACHE20

USES=		python:3.5+
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
